spring:
  application:
    name: order
  datasource:
    username: root
    password: JDWL_20160129@
    url: jdbc:mysql://192.168.10.150:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.10.150
    port: 5672
    username: ajutong-log
    password: JDWL_20160129@
  redis:
    host: 192.168.10.150
    port: 6379
    password: 1234
env:
  test1122
girl:
  name: mo
  age: 17
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  
