spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: JDWL_20160129@
    url: jdbc:mysql://mysql:13306/springCloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ajutong-log
    password: JDWL_20160129@
  redis:
    host: redis
    port: 6379
    password: 1234
  jpa:
    show-sql: true
girl: 
  name: ha
  age: 38
