spring:
  datasource:
    username: root
    password: JDWL_20160129@
    url: jdbc:mysql://192.168.10.150:13306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ajutong-log
    password: JDWL_20160129@
  redis:
    host: redis
    port: 6379
    password: 1234
  jpa:
    show-sql: true
girl: 
  name: ha
  age: 38
