spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.10.150:13306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.10.150
    port: 5672
    username: ajutong-log
    password: JDWL_20160129@
  redis:
    host: redis
    port: 6379
    password: 1234
girl:
  name: mot
  age: 17
